IF NOT EXISTS (SELECT 1 FROM PERSONNEL WHERE PER_LNAME = 'CAGABAY')
BEGIN
    INSERT INTO PERSONNEL (
        PER_ID, PER_LNAME, PER_FNAME, PER_MNAME, PER_DATE_HIRED,
        PER_SSS_NO, PER_DESIG, PER_TIN_NO, PER_ADDRESS,
        PER_BIRTH_DATE, PER_STATUS, PER_DISB_LIMIT, PER_PICTURE
    )
    SELECT
        ISNULL(MAX(PER_ID), 0) + 1, 'CAGABAY', 'CAGABAY', 'B',
        '2025-04-16', 'N/A', 0, 'N/A', '', '2016-01-01', NULL, 0, NULL
    FROM PERSONNEL
END




IF NOT EXISTS (SELECT 1 FROM saf WHERE TLRNAME = 'CAGABAY')
BEGIN
    INSERT INTO saf (
        TLRNAME, TLRLEVEL, DISBLIMIT, CASH_FROM_CASHIER,
        CASH_FROM_TELLER, CASH_ON_HAND, USER_PERID,
        ALREADY_BALANCE, BEG_BALANCE, isloggedin,
        computername
    )
    VALUES (
        'CAGABAY', 0, 0, 0, 0, 0, (select per_id from PERSONNEL where PER_LNAME ='CAGABAY'), 0, 0, 0, NULL
    )
END


