CREATE TABLE [dbo].[refmapping](
	[reftype] [varchar](50) NULL,
	[title] [varchar](100) NULL,
	[refid] [varchar](20) NULL,
	[localcode] [varchar](20) NULL
) ON [PRIMARY]



insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Animal Production (Other Animals)','BT125','53');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Chicken Livestock','BT132','54');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cow Raising','BT135','55');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Goat Fattening','BT140','57');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Hatchery','BT144','58');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Poultry','BT158','61');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','62');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cacao Production','BT8','63');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cacao Production','BT8','64');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Calamansi Plantation','BT9','65');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Calamansi Plantation','BT9','66');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','67');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','68');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Abaca Production','BT1','69');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Abaca Production','BT1','70');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','African Tree','BT2','71');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','African Tree','BT2','72');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','73');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bamboo Craft','BT254','74');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Banana Plantation','BT3','75');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Banana Plantation','BT3','76');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bonsai','BT7','77');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cassava Plantation','BT11','78');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cassava Plantation','BT11','79');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cauliflower Production','BT13','80');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cauliflower Production','BT13','81');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','83');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','84');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','85');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','86');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coffee Production','BT21','88');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coffee Production','BT21','89');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Copra Plantation','BT23','90');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Copra','BT22','91');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Corn Dust','BT28','92');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Corn Dust','BT28','93');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Corn Dust','BT28','94');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','95');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','96');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','97');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','98');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Eggplant Farming','BT34','99');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Falcata Plantation','BT35','100');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Falcata Plantation','BT35','101');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flower Farm/Production','BT43','103');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flower Farm/Production','BT43','104');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fruits Plantation','BT48','105');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fruits Plantation','BT48','106');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Gardening/Lanscaping','BT51','107');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Garlic And Onion Production','BT53','108');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','109');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','110');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lemon Production','BT57','111');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lemon Production','BT57','112');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lemon Production','BT57','113');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','114');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mongo Production','BT66','119');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mushroom','BT67','120');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mushroom','BT67','121');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ornamental Plants','BT72','122');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Palm Oil','BT75','123');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Palm Oil','BT75','124');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Palm Oil','BT75','125');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Papayahan','BT77','126');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Papayahan','BT77','127');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Peanut','BT78','128');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Peanut','BT78','129');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','130');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pinyahan','BT81','131');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pinyahan','BT81','132');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Root Crops','BT90','134');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Root Crops','BT90','135');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rubber','BT92','136');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rubber Farming','BT93','137');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Seedlings','BT99','138');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sugarcane','BT106','139');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sugarcane','BT106','140');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tobacco','BT108','141');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tobacco','BT108','142');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','143');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','144');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vegetable Farming','BT115','145');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vegetable Farming','BT115','146');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Bill','BT474','147');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Bill','BT474','148');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Bill','BT474','149');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bonsai','BT7','150');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Crab Fattening','BT172','151');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cultured Green Saltwater Mussel','BT173','152');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Baklad (Fish Cage)','BT171','153');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fish Production','BT178','154');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','156');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sardines','BT182','157');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Seaweeds','BT183','158');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salt Making','BT97','167');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salt Refinery','BT98','168');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Auto Parts Shop','BT662','169');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Radiator','BT982','171');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vulcanizing','BT940','172');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Livelihood/Livestock','BT152','174');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','176');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dried Fish Vending','BT557','177');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dried/Smoked Fish Vending','BT560','178');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Egg Vending','BT564','179');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Live Fish Vending','BT590','180');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Supplement Dealer','BT578','181');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Frozen Foods','BT580','182');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fruit Vending','BT584','183');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Honey (Vending)','BT148','184');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Macaroni Deliver','BT1071','185');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Meat Vending','BT596','186');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell (Rice Dealer/Retailer)','BT522','187');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Root Crops','BT90','188');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salted Eggs','BT1089','189');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Seafood Vending','BT615','190');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Seasonings Vending','BT617','191');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Seaweeds','BT183','192');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Smoke Fish','BT228','193');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Softdrink (Distributor)','BT621','194');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Spices Vending','BT647','195');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vegetable Farming','BT115','197');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vinegar Manufacture','BT237','198');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Yakult Vending','BT645','200');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Abaca Vending','BT650','201');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Accessories Vending','BT651','202');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Agricultural Products And Supply','BT652','203');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Agrivet Supply','BT653','204');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Glass And Aluminum Supply','BT782','205');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Amakan (Bamboo Matt)Vending','BT657','206');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Feeds Dealer','BT753','207');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Antique Making','BT247','208');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Appliance Agent','BT1184','209');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Assorted Goods','BT660','210');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Automobile Shop','BT664','211');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cake Baking','BT194','212');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Balloons And Party Maker','BT252','213');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bamboo Craft','BT254','214');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bamboo Craft','BT254','215');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','216');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Basket/Abaca Weaving','BT260','217');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Battery Shop','BT668','218');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beauty/Cosmetics Products Vending','BT674','219');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','220');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Billiard','BT1226','222');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','BlackSmith','BT416','223');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Book Selling','BT676','225');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Botica','BT679','226');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bridal Shop','BT681','227');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Broom Vending','BT682','228');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Auto Supplies','BT663','229');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell (Bags Etc.)','BT687','230');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell (Bags Etc.)','BT687','231');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','233');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','234');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','235');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell (Silver Jewelry)','BT695','236');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell (Medicine)','BT694','237');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','238');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell RTW','BT700','239');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','240');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','241');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','242');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','243');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','245');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Candle Vending','BT702','246');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Carpenter','BT489','247');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','248');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cellophane','BT269','249');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','251');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coco Lumber Production','BT14','253');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coco Lumber Production','BT14','254');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Computer','BT1156','255');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Concrete Products','BT717','256');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Construction Business','BT718','257');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Construction Business','BT718','258');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Contractor','BT491','259');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','260');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cosmetic Dealer','BT723','261');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cultured Green Saltwater Mussel','BT173','262');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Curtain Selling','BT728','263');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','264');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dental Aide','BT1210','265');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beauty Products Seller','BT670','266');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Diswashing Liquid','BT277','267');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Drugstore','BT733','268');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dvd Accessories','BT918','269');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electrical Supplies','BT737','270');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Eye Wear','BT749','271');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Farm Supply','BT751','272');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','273');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fire Extinguisher Vendor','BT759','274');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Firewood Vending','BT760','275');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fireworks','BT283','276');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fishing Boat/Pump Boat','BT1149','277');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flower Farm/Production','BT43','278');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flower Farm/Production','BT43','279');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flower Farm/Production','BT43','280');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Warmer Vending','BT763','281');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Footwear','BT765','282');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','283');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Furniture','BT378','284');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Gasolina Vending/Retailing','BT768','285');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','General Merchandise','BT779','286');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Glass And Aluminum','BT780','287');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Gravel And Sand','BT789','288');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Herbal Medicine Vending','BT798','291');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Hollow blocks Vending','BT801','292');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','293');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','294');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','295');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','296');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Kalakat Vending','BT807','297');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','298');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Kitchen Wares','BT429','299');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Kitchen Wares','BT429','300');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','301');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Limestone Selling','BT808','302');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Loading Business','BT813','303');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','LPG Dealer','BT816','304');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','305');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lumber','BT58','306');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','307');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Motorcycle Shop','BT967','309');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','310');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Native Delicacies','BT1076','311');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Newspaper Vending','BT849','312');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Nipa Production','BT70','313');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Loading Business','BT813','314');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Palm Oil','BT75','315');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pebbles','BT855','316');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beauty Products/Perfume','BT671','317');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pet Shop','BT931','318');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Plant Vending','BT929','319');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Plastic Ware Peddlers','BT859','320');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','321');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rattan Making','BT319','322');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','323');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','E-Loader/Retailer','BT748','324');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rolling Store','BT867','325');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rope Retailer','BT869','326');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rubber Farming','BT93','327');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sack Making','BT326','328');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','329');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','330');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sari-Sari Store','BT882','331');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','School Canteen','BT1091','332');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sewing Machine','BT368','333');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Shoe/Slipper Vendor','BT890','334');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sidecar Making','BT337','335');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sidecar Making','BT337','336');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sim Card Dealer','BT893','337');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Souvenir Items','BT898','338');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','339');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Steel Fabrication','BT434','340');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Street Food Vending','BT1097','341');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','342');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','343');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Toys And Balloons','BT907','344');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Upholstery Shop','BT984','345');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vendo Machine','BT1147','346');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Distributor','BT475','347');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bakery','BT251','348');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Balut/Penoy Vendor','BT1001','349');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Banana Plantation','BT3','350');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cakes And Pastries','BT196','351');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','352');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Candy Factory','BT197','353');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cashew Processing','BT199','355');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cassava Plantation','BT11','356');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Chicharon Vending','BT1028','357');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','358');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','359');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','360');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','361');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coffee Production','BT21','363');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','364');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Corn Dust','BT28','365');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fish Processing','BT205','366');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Driller','BT490','367');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Processing','BT206','368');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','369');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Home Made Cakes','BT208','370');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','371');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ice Plant','BT213','374');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ice Pop/Ice Candy Making','BT214','375');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lumpia Wrapper Making','BT217','377');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','378');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Meat Vending/Meat Shop','BT597','379');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','380');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Native Delicacies','BT1076','381');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','382');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Panutsa','BT221','383');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pastillas Making','BT222','384');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Peanut Farming','BT79','385');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Peanut Farming','BT79','386');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pili Vending','BT609','387');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rattan','BT318','388');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rice Mill','BT86','389');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rice Production','BT87','390');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salt Making','BT97','391');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salted Eggs','BT1089','392');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sardines','BT182','393');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Siopao','BT1093','394');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Smoke Fish','BT228','395');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Soya Milk','BT229','396');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Taho Vending','BT1098','398');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tuna Products','BT236','399');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vinegar Manufacture','BT237','400');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Yema Vending','BT646','402');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Abaca Vending','BT650','403');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Accessories Vending','BT651','404');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Agsam Craft','BT242','405');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Aluminum Supplies','BT655','406');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Amakan (Bamboo Matt)Vending','BT657','407');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Anchor Making','BT246','408');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Antique Making','BT247','409');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Appliance Agent','BT1184','410');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','411');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bag Weaving','BT250','412');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','413');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Balloons And Party Maker','BT252','414');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','415');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bamboo Craft','BT254','416');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Battery Shop','BT668','418');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beauty Product','BT669','419');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','420');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','BlackSmith','BT416','421');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','422');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Boat Making','BT262','423');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','424');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','425');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Broom Making','BT263','426');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buri Crafts','BT264','427');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Candle Vending','BT702','429');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cartoon Making','BT1229','430');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cassava Plantation','BT11','431');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ceramics Vending','BT707','432');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Chemical Products','BT273','433');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Chicken Livestock','BT132','434');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','436');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','437');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','438');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coconut','BT15','439');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coffee Production','BT21','440');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','441');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Curtain Selling','BT728','442');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','443');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Denture Laboratory','BT1217','444');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Distilled Water And Solution','BT487','445');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','446');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','447');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','448');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Falcata Plantation','BT35','449');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','450');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Figurine','BT281','451');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','452');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fish Net Making','BT284','453');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Floorwax Making','BT762','454');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Handicraft Making','BT291','455');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Furniture','BT378','456');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','457');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Garments','BT287','458');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Glass And Aluminum','BT780','459');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Goldsmith','BT425','460');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Grinder','BT791','461');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','463');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Handicraft','BT290','464');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Herbal Medicine Vending','BT798','465');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Hollow blocks Vending','BT801','466');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','467');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ironsmith/Sundang Making','BT428','468');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','470');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lamp Maker','BT301','471');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lampakanay','BT303','472');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Land Renting','BT1204','473');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lease Space Rental','BT993','474');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','475');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','476');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','477');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','478');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Metal Craft','BT431','480');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Metal Craft','BT431','481');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','482');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','483');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Native Delicacies','BT1076','484');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Newspaper Vending','BT849','485');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Nipa Production','BT70','486');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Papayahan','BT77','487');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Picture Lamination','BT408','488');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','489');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pili Vending','BT609','490');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','491');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Plastic Ware Peddlers','BT859','492');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pottery Making/Vending','BT862','493');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rattan Making','BT319','494');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','495');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','496');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rubber Farming','BT93','498');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rubber','BT92','499');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rags Making','BT317','500');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sawali/Nipa Making','BT328','501');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','502');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Seaweeds','BT183','503');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Shoe/Slipper Vendor','BT890','504');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sidecar Making','BT337','505');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Souvenir Items','BT898','506');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Steel Fabrication','BT434','507');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Stone Craft','BT341','508');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','509');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Straw Making','BT342','510');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tailoring','BT374','512');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','513');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tinsmith','BT437','514');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tnalak Weaving','BT343','515');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','516');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Toys And Balloons','BT907','517');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','518');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Wood Carving','BT350','519');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','520');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Art And Sign','BT393','521');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','522');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Boat Maintenance','BT389','524');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Book Binding','BT439','525');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fishing Boat/Pump Boat','BT1149','526');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Glass And Aluminum','BT780','527');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Motorboat','BT1150','528');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Printing','BT409','530');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Printing','BT409','531');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sound And Disco Mobile','BT1235','532');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Welding Shop','BT945','533');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','534');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electrical Supplies','BT737','535');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','536');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Apartment Rental','BT985','538');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','540');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cottage Rental','BT991','541');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','542');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','543');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','544');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','546');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lease Space Rental','BT993','547');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beach Resort','BT1224','548');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Transport Services','BT1128','549');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Balut/Penoy Vendor','BT1001','550');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Banana Plantation','BT3','551');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Barbecue Stall','BT1008','553');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beverage Retailers','BT504','554');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bread Vending','BT508','555');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buko Juice','BT1012','556');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Burger Machine','BT1015','557');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cafeteria','BT1018','558');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cake Vending','BT530','559');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Canteen/Carenderia','BT1020','560');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','561');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coffee Production','BT21','562');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coffee Production','BT21','563');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','564');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','565');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Vending','BT1045','566');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Catering','BT1041','567');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','568');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','569');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Cart','BT1040','570');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','571');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Halo-Halo','BT1048','575');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ice Drop Vending','BT1054','577');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ice/Ice Candy','BT1056','579');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','580');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Kakanin/Snack Vending','BT1059','581');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lechon Dealer','BT1063','583');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','585');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Nata De Coco','BT1075','586');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Native Delicacies','BT1076','587');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','588');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Panciteria','BT1078','589');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pili Nut Candy Vending','BT608','591');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pili Vending','BT609','592');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Restaurant','BT1082','593');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rice Cake Vending','BT611','594');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salad Dealer','BT1087','595');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Siopao Making','BT227','596');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Snack Hauz','BT1094','597');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sofdrinks/Hard Drinks Vending','BT620','598');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Street Food Vending','BT1097','599');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Taho Vending','BT1098','600');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','601');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Yema Vending','BT646','602');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bar','BT1006','603');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cartoon Making','BT1229','605');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Construction Business','BT718','607');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','608');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','House For Rent','BT992','609');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','610');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','MACHINE/ WATER PUMP','BT480','611');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','612');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sound And Disco Mobile','BT1235','613');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Swine','BT166','614');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tablia','BT231','615');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Ticketing Office','BT1200','616');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','617');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tourist Boat','BT1199','618');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Travel Agency','BT1203','619');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Video Shop','BT1238','620');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Videoke Bar','BT1239','621');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Amusement','BT1222','622');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Arcade','BT1246','623');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beach Resort','BT1224','624');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bike Rentals','BT1225','625');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Billiard','BT1226','626');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cartoon Making','BT1229','627');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cartoon Making','BT1229','628');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Coco Lumber Production','BT14','629');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Entertainment','BT1231','630');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','631');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','632');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','633');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','634');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Night Club','BT1250','635');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Painting','BT1233','636');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Sound And Disco Mobile','BT1235','637');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Video Shop','BT1238','638');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Videoke Bar','BT1239','639');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Carpenter','BT489','640');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Contractor','BT491','641');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','House For Rent','BT992','642');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','House For Rent','BT992','643');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','644');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','645');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','General Merchandise','BT779','646');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','647');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','648');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','649');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','650');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','651');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Insurance','BT1176','652');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','653');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Monggo Farming','BT65','654');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','655');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Globe/Smart Money Padala','BT788','656');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','657');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','658');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','659');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dental Aide','BT1210','661');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','663');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Medical Supply','BT821','665');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Medical Supply','BT821','666');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Optical','BT1219','667');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','668');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','669');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','670');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cable Service Maintenance','BT1152','671');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Computer Rentals/Internet Shop','BT1163','672');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','673');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','674');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Apartment Rental','BT985','675');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Appliance Agent','BT1184','676');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Barbershop','BT1251','677');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beautician','BT1252','678');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','679');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electronics Repair Shop','BT1264','681');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cut Flower','BT33','682');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Funeral Parlor','BT1266','683');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Home Service','BT1270','684');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Key Duplication, Key Maker','BT1271','685');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','686');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Laundry','BT1193','687');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pest Control/Insecticides','BT856','688');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','689');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','690');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salon','BT1293','691');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Shoe Repair','BT334','692');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Advertisement','BT1183','694');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Painting','BT1233','695');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Photography','BT1182','696');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','697');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','698');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','699');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Interior Design','BT1180','700');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Land Renting','BT1204','701');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Land Renting','BT1204','702');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Real Estate','BT1179','703');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Real Estate','BT1179','704');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','705');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bus Operator','BT1103','706');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cartoon Making','BT1229','707');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','709');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Jeepney','BT1109','710');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pedicab','BT1119','711');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','712');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Taxi','BT1126','713');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tricycle','BT1132','714');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Trucking','BT1142','715');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Junk Shop','BT458','717');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Scrap Materials','BT461','718');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Septic Tank','BT466','719');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Street Food Vending','BT1097','720');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mineral Water','BT468','721');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mineral Water','BT468','722');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Purified Water','BT470','723');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Distributor','BT475','724');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Bill','BT474','725');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Purification','BT476','726');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Bill','BT474','727');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1552');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1565');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Accessories Vending','BT651','1566');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1567');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1568');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1569');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Agricultural Products And Supply','BT652','1570');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Animal Production (Other Animals)','BT125','1571');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Antique Making','BT247','1572');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Apartment Rental','BT985','1573');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1574');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Auto Parts Shop','BT662','1575');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bakery','BT251','1576');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bakery','BT251','1577');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bamboo Craft','BT254','1578');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bamboo Craft','BT254','1579');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Barbeque Vending','BT1010','1580');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1581');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beach Resort','BT1224','1582');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Beauty Product','BT669','1583');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1584');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bilao (Basket) Vending','BT675','1585');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','BlackSmith','BT416','1586');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Books Dealer','BT677','1588');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Bridal Shop','BT681','1589');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Broiler','BT127','1590');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1591');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1592');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1593');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1594');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1595');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1596');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1597');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy And Sell','BT683','1598');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Canteen','BT1019','1600');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Carinderia','BT1025','1603');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1606');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Charcoal Dealer','BT708','1607');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cigaratte Vendor','BT712','1608');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Computer','BT1156','1609');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Construction Business','BT718','1610');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Copra','BT22','1611');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Cosmetic Dealer','BT723','1612');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Curtain Selling','BT728','1613');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1614');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dental Aide','BT1210','1615');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1616');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dress Making','BT355','1617');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dress Shop','BT360','1618');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Dry Goods','BT734','1619');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1620');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electrical Supplies','BT737','1621');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electrical Supplies','BT737','1622');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electrical Supplies','BT737','1623');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Electrical Supplies','BT737','1624');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1625');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1626');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1627');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Farm Financing','BT36','1628');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Feeds','BT752','1630');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fertilizer Vending','BT758','1631');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1632');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fish Vending','BT573','1633');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fish Vending','BT573','1634');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flower Farm/Production','BT43','1635');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Flowers','BT47','1636');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Food Vending','BT1045','1637');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Frozen Foods','BT580','1638');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Frozen Foods','BT580','1639');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Fruit Vending','BT584','1640');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Funeral Parlor','BT1266','1641');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Furniture','BT378','1642');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1643');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Garden','BT50','1644');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Garden','BT50','1645');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Gasolina Vending/Retailing','BT768','1646');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Gasolina Vending/Retailing','BT768','1647');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1648');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Handicraft','BT290','1650');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Handicraft','BT290','1651');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Herbal Medicine Vending','BT798','1652');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','House For Rent','BT992','1654');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1655');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1657');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Insurance','BT1176','1658');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Iron Works','BT426','1659');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1661');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1662');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Land Renting','BT1204','1663');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Laundry','BT1193','1665');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Laundry','BT1193','1666');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Loading Business','BT813','1667');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Lumber','BT58','1668');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mais Farming','BT59','1669');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Massage','BT1280','1672');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Meat Vending','BT596','1673');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Medicine','BT823','1674');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Merchandise','BT829','1675');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mineral Water','BT468','1676');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1677');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1678');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Night Club','BT1250','1679');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1680');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1681');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Optical','BT1219','1682');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1683');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1684');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1685');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1686');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Painting','BT1233','1687');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Panutsa','BT221','1688');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Party Needs','BT852','1689');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pastillas Making','BT222','1690');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pedicab','BT1119','1691');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pedicab','BT1119','1692');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Peryahan','BT1234','1693');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Peryahan','BT1234','1694');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Photo Shop Studio','BT403','1695');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Photo Shop Studio','BT403','1696');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Pillow Making','BT365','1697');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1698');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Plant Vending','BT929','1699');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Poultry','BT158','1700');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Poultry','BT158','1701');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1702');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1703');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Real Estate','BT1179','1704');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Repair Shop','BT451','1705');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Repair Shop','BT451','1706');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Repair Shop','BT451','1707');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Restaurant','BT1082','1708');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1709');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rice Production','BT87','1710');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','RTW Store','BT873','1711');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rug Making','BT325','1712');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Rug Making','BT325','1713');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Salt Making','BT97','1714');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1715');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','School Canteen','BT1091','1716');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Shoe Repair','BT334','1719');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1720');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Softdrink (Distributor)','BT621','1721');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Softdrink (Distributor)','BT621','1722');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Steel Fabrication','BT434','1723');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tablia','BT231','1724');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tailor Machine','BT371','1725');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tailor Machine','BT371','1726');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tailoring','BT374','1727');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1728');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1729');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1730');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Transport Services','BT1128','1731');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Tricycle','BT1132','1732');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1733');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Uling Vending','BT912','1734');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Upholstery Shop','BT984','1735');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Upholstery Shop','BT984','1736');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vegetable Farming','BT115','1737');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vegetable Farming','BT115','1738');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Videoke Bar','BT1239','1739');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Vulcanizing','BT940','1740');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Refilling Station','BT477','1741');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Water Station','BT478','1742');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1743');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Xerox Machine','BT415','1744');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Xerox Machine','BT415','1745');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Mining Materials','BT834','1746');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1747');
insert into refmapping (reftype,title,refid,localcode)values('LoanBusinessType','Buy and Sell','BT683','1748');
